/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.example

import org.springframework.boot.SpringApplication


class App {
    static void main(String[] args) {
       SpringApplication.run(App.class, args)
    }
}
